name: Publish

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Github Automatic Npm Release Action
        uses: donmahallem/github-release-action@v1.0.0
        with:
          github_secret: ${{ secrets.github_secret }}
